execute if score @s time matches 40 run summon bedwars:text_display "§e在§c40§e秒后产出" ~~3.5~
execute if score @s time matches 39 run summon bedwars:text_display "§e在§c39§e秒后产出" ~~3.5~
execute if score @s time matches 38 run summon bedwars:text_display "§e在§c38§e秒后产出" ~~3.5~
execute if score @s time matches 37 run summon bedwars:text_display "§e在§c37§e秒后产出" ~~3.5~
execute if score @s time matches 36 run summon bedwars:text_display "§e在§c36§e秒后产出" ~~3.5~
execute if score @s time matches 35 run summon bedwars:text_display "§e在§c35§e秒后产出" ~~3.5~
execute if score @s time matches 34 run summon bedwars:text_display "§e在§c34§e秒后产出" ~~3.5~
execute if score @s time matches 33 run summon bedwars:text_display "§e在§c33§e秒后产出" ~~3.5~
execute if score @s time matches 32 run summon bedwars:text_display "§e在§c32§e秒后产出" ~~3.5~
execute if score @s time matches 31 run summon bedwars:text_display "§e在§c31§e秒后产出" ~~3.5~
